### ISSUE TITLE
Products REST API NPE

### ISSUE THREAD

**Issue by samhamilton** [moqui/moqui-runtime#18]
Hi David - it looks like your changes might have kicked in the following error

If you install a demo copy of the following components 
```
git clone https://github.com/moqui/moqui-framework.git moqui
git clone https://github.com/moqui/moqui-runtime.git moqui/runtime
git clone https://github.com/moqui/mantle-udm.git runtime/component/mantle-udm
git clone https://github.com/moqui/mantle-usl.git runtime/component/mantle-usl
```
Then give john.doe permissions to access the Products API
```
<moqui.security.ArtifactGroup artifactGroupId="PRODUCT_API" description="Product REST API"/>
<moqui.security.ArtifactGroupMember artifactGroupId="PRODUCT_API" artifactName="mantle\.product\..*"
                                        nameIsPattern="Y" artifactTypeEnumId="AT_ENTITY" inheritAuthz="Y"/>
<moqui.security.ArtifactAuthz artifactAuthzId="PRODUCT_AUTHZ_ALL" userGroupId="ADMIN" artifactGroupId="PRODUCT_API"
                                        authzTypeEnumId="AUTHZT_ALWAYS" authzActionEnumId="AUTHZA_ALL"/>
```
Now CURL one of the default products 
```
curl -X GET -u john.doe:moqui http://localhost:8080/rest/m1/products/10000
```
And you get the following error
```
--- 17:07:55.727 [andlerThread[9]] WARN      org.moqui.impl.context.WebFacadeImpl
 General error in entity REST: java.lang.NullPointerException
java.lang.NullPointerException
	at org.moqui.impl.entity.EntityFindBase.oneMaster(EntityFindBase.groovy:774) ~[moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.entity.EntityFacadeImpl.rest(EntityFacadeImpl.groovy:1274) ~[moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.context.WebFacadeImpl.handleEntityRestCall(WebFacadeImpl.groovy:793) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.context.WebFacade$handleEntityRestCall.call(Unknown Source) [moqui-framework-1.6.3.jar:1.6.3]
	at rest_xml_transition_m1_actions.run(rest_xml_transition_m1_actions:5) [script:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:67) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.screen.ScreenDefinition$TransitionItem.run(ScreenDefinition.groovy:707) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:229) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:223) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:336) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:167) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:73) [moqui-framework-1.6.3.jar:1.6.3]
	at org.moqui.impl.webapp.MoquiServlet.doGet(MoquiServlet.groovy:42) [moqui-framework-1.6.3.jar:1.6.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:693) [moqui-1.6.3.war:1.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806) [moqui-1.6.3.war:1.2]
	at net.winstone.core.ServletConfiguration.execute(ServletConfiguration.java:270) [moqui-1.6.3.war:1.7.0]
	at net.winstone.core.SimpleRequestDispatcher.forward(SimpleRequestDispatcher.java:290) [moqui-1.6.3.war:1.7.0]
	at ntone.core.listener.RequestHandlerThread.processRequest(RequestHandlerThread.java:212) [moqui-1.6.3.war:1.7.0]
	at net.winstone.core.listener.RequestHandlerThread.run(RequestHandlerThread.java:143) [moqui-1.6.3.war:1.7.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at net.winstone.util.BoundedExecutorService$1.run(BoundedExecutorService.java:81) [moqui-1.6.3.war:1.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
--- 17:07:55.730 [andlerThread[9]] INFO    org.moqui.impl.screen.ScreenRenderImpl
 Finished transition [rest, m1, products, 10000] in 0.005 seconds; type none response.
```

Many thanks
Sam

**Comment by jonesde** [comment]
This is fixed in commit #e7a72d9. Looks like an error that has been around since the original entity master API additions, a NPE when no matching master record is found.
