### ISSUE TITLE
Logout error - Invalid for read: id=node025ehkn4dbkzmq3loqdkq4e40 not resident

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#72]
This error occurs after logging out. Application works normally and user is logged out as expected, the error is logged.

![logout_errorstack](https://cloud.githubusercontent.com/assets/14863763/21574433/f318e6fe-cef2-11e6-9b27-457ab7ddc949.png)

![logout_loginxml](https://cloud.githubusercontent.com/assets/14863763/21574435/f4ef06e8-cef2-11e6-93b5-bf025eb1751b.png)

2016-12-31 00:40:59.330:WARN:oejs.session:qtp787604730-44: 
java.lang.IllegalStateException: Invalid for read: id=node025ehkn4dbkzmq3loqdkq4e40 not resident
	at org.eclipse.jetty.server.session.Session.checkValidForRead(Session.java:629)
	at org.eclipse.jetty.server.session.Session.getAttribute(Session.java:649)
	at org.moqui.impl.webapp.MoquiSessionListener.sessionDestroyed(MoquiSessionListener.groovy:56)
	at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1056)
	at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1230)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.invalidateAll(DefaultSessionIdManager.java:474)
	at org.eclipse.jetty.server.session.Session.invalidate(Session.java:862)
	at org.apache.shiro.web.session.HttpServletSession.stop(HttpServletSession.java:113)
	at org.apache.shiro.session.ProxiedSession.stop(ProxiedSession.java:107)
	at org.apache.shiro.subject.support.DelegatingSubject$StoppingAwareProxiedSession.stop(DelegatingSubject.java:419)
	at org.apache.shiro.mgt.DefaultSecurityManager.stopSession(DefaultSecurityManager.java:581)
	at org.apache.shiro.mgt.DefaultSecurityManager.logout(DefaultSecurityManager.java:567)
	at org.apache.shiro.subject.support.DelegatingSubject.logout(DelegatingSubject.java:363)
	at org.moqui.impl.context.UserFacadeImpl.popUser(UserFacadeImpl.groovy:702)
	at org.moqui.impl.context.UserFacadeImpl.logoutUser(UserFacadeImpl.groovy:503)
	at org.moqui.context.UserFacade$logoutUser$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at component___webroot_screen_webroot_Login_xml_transition_logout_actions.run(component___webroot_screen_webroot_Login_xml_transition_logout_actions:8)
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67)
	at org.moqui.impl.screen.ScreenDefinition$TransitionItem.run(ScreenDefinition.groovy:731)
	at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:253)
	at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:247)
	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:370)
	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:159)
	at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:79)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:530)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
00:40:59.341  INFO 787604730-44               o.m.i.s.ScreenRenderImpl Transition Login/logout in 50ms, redirecting to screen path URL: http://localhost:8080

**Comment by jonesde** [comment]
It looks like in the latest version of Jetty (9.4.0), with the default configuration at least (and maybe there is some sort of option for this) the session attributes are invalidated before the sessionDestroyed() method is called. That goes against the Servlet API javadocs which say: "Notification that a session is about to be invalidated." This may be a bug that will be fixed in a later release.

Anyway, yes I've seen this an implemented a workaround in the MoquiSessionListener, which is probably a more stable approach anyway across different app servers. This fix is in a forked client repository and should be merged in a few days (long before any sort of release).
